### ISSUE TITLE
security query

### ISSUE THREAD

**Issue by simonmcnair** [lisenet/kubernetes-homelab#59]
Out of curiosity your repo seems littered with keys and passwords.  Is that intentional ?  I'm assuming they're different in your environment, but was just curious.

Cheers

**Comment by lisenet** [comment]
Can you give me an example please?

**Comment by simonmcnair** [comment]
do a search for ssh in the repo and there are some keys in there.  I'm not a security expert, and I have no issue with the keys being there, just wondered if you'd changed them in your own environments.

**Comment by lisenet** [comment]
Thanks, appreciated. I had a quick  look, and there should be no **private** SSH keys stored in this repo because there is no need to do that (not that I can remember anyway).

There will be **public** SSH keys recorded here intentionally because, well, it's my homelab, and I find it helfpul :) These are public keys therefore not security risk from my point of view. They are virtually useless without the private keys. I think areas that have them would be Packer kickstart files and Ansible playbooks that configure users.

What I do change in my env is K8s secrets stored in YAML files. You will find that these are randomly generated. If I leave them blank, deployments will fail and it is just not good as people will message me saying "it does not work". My preference therefore is to have random secrets stored in the master branch so that you could get services deployed (you should change the secrets for your env obvs). In my homelab env I use a different git branch (that's not public) that has my secrets and not the ones in the master branch.

**Comment by simonmcnair** [comment]
Thanks for the clarification, appreciate it.

**Comment by lisenet** [comment]
Your question got me thinking really. I think I'll look into migrating K8s secrets (and perhaps even SSH public keys) to Hashicorp Vault rather than hardcoding them in the repo (despite them being random).

**Comment by simonmcnair** [comment]
> Your question got me thinking really. I think I'll look into migrating K8s secrets (and perhaps even SSH public keys) to Hashicorp Vault rather than hardcoding them in the repo (despite them being random).

I'd appreciate your final thoughts on this.  I'm new to the whole iac/devops thing having been a windows guy for the last 20 odd years.  I'm happy using linux, Docker, PXE & proxmox, but putting the whole thing together cohesively is making my head hurt to be honest.  I'm working my way through your homelab but it's tough going, especially when it's a work in progress, and things are changing from where you started, to where you are.

**Comment by lisenet** [comment]
You learn by trying, that's the only way. By the time you configure your homelab, techologies have changed and you start over. 

I think I've re-built my homelab at least three times, it's a living thing and never a finished product. I moved from VirtualBox to Xen to Proxmox to KVM and I think I might move to just running containers at some point. I migrated from Bash automation to Puppet to Ansible to Terraform and I'm sure something else will be there tomorrow. Docker has been dropped by K8s so people are migrating to Podman. It's tough going, you're right, I think that's just the way DevOps. You need to know everything.
